import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { homeDataResponseType } from '@/src/types/types';
import Request from '@/src/helper/Request';
import Api from '@/src/constants/Api';
import MyProvider from '@/src/context/MyProvider';
import Header from '@/src/common/Header';
import SetData from '@/src/components/SetData';
import Footer from '@/src/common/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MyProvider>
      <SetData />
      {<Header />}
      {children}
      <Footer />
    </MyProvider>
  );
}
